# These are supported funding model platforms

github: 
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
custom: ['https://pizza-soft.ru/2019/11/04/codereuse/']
