# These are supported funding model platforms

github: 
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
custom: ['https://portal.pizza-soft.ru/index.php/en/contribute-to-reuse','https://pizza-soft.ru/2019/11/04/codereuse/','https://solutionsmanagerit.github.io/ReUse/','https://solutionsmanagerit.github.io/ReUse_Net/']
